[global]
# Development settings
developmentMode = false
logLevel = "info"

[server]
# Server settings
port = 8501
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200

[browser]
# Browser settings
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[theme]
# App theme
primaryColor = "#FF6B35"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"